/**
 * 
 */
public enum Province {ALBERTA, BRITISHCOLUMBIA, MANATOBA, NEWBRUNSWICK, NEWFOUNDLANDANDLABRABOR, NORTHWESTTERRITORIES, NOVASCOTIA, NUNAVUT, ONTARIO, PRINCEEDWARDISLAND, QUEBEC, SASKATCHUWAN, YUKON} 